### ISSUE TITLE
Fugitive's `:Gstatus` breaks

### ISSUE THREAD

**Issue by hkupty** [neovim/python-client#117]
When calling `:Gstatus`, neovim breaks with the following error message:

```
Error detected while processing function <SNR>44_setupOmni..provider#python#Call:                          
line 12:                              
Channel 1 returned a response that doesn't have a matching request id. Ensure the client is properly synchronized :
Exception in thread Thread-1:     
Traceback (most recent call last):         
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner    self.run()
  File "<string>", line 382, in run     
  File "<string>", line 116, in getUpstreamRepoURI                    
  File "<string>", line 34, in getRepoURI             
  File "/usr/lib/python2.7/site-packages/neovim/api/nvim.py", line 233, in buffer
    return self._session.request('vim_get_current_buffer')                                                     
  File "/usr/lib/python2.7/site-packages/neovim/api/common.py", line 219, in request
    return walk(self._in, self._session.request(name, *args), self, name,
  File "/usr/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 72, in request
    v = self._yielding_request(method, args)
  File "/usr/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 137, in _yielding_request
    return parent.switch()                                 
AttributeError: 'NoneType' object has no attribute 'switch'
```

**Comment by antoyo** [comment]
In my case, I only see an empty preview window after typing the `:Gstatus` command.
Here is my nvim version.

```
:version                                                                                                               
NVIM 0.0.0-alpha+201507312130 (compiled Aug  1 2015 17:52:30)
Commit: d4396acedb213209aee4693e196f1952bbc88ff5
```

**Comment by hkupty** [comment]
It seems that it was a temporary bug or something that is already corrected. Closing.
