### ISSUE TITLE
Mention prerequisites for installing the neovim package

### ISSUE THREAD

**Issue by expipiplus1** [neovim/python-client#143]
It might be useful to mention that `python-dev` and `python3.5-dev` need to be installed before the pip command on Debian.

**Comment by bfredl** [comment]
they shouldn't be necessary, what error do you get if you don't have `python-dev` ?

**Comment by bfredl** [comment]
this might have been for the cythonize build step, but this is moved to neovim/python-gui now. Reopen if still an issue for this repo.

**Comment by expipiplus1** [comment]
Will do, thanks for looking.

**Comment by expipiplus1** [comment]
`pip2 install neovim` without `python-dev` on a clean Ubuntu machine fails with this output.

```
$ sudo pip2 install neovim
Downloading/unpacking neovim
  Downloading neovim-0.1.5.tar.gz
  Running setup.py (path:/tmp/pip_build_root/neovim/setup.py) egg_info for package neovim
    
Downloading/unpacking msgpack-python>=0.4.0 (from neovim)
  Downloading msgpack-python-0.4.7.tar.gz (126kB): 126kB downloaded
  Running setup.py (path:/tmp/pip_build_root/msgpack-python/setup.py) egg_info for package msgpack-python
    
Downloading/unpacking trollius (from neovim)
  Downloading trollius-2.1.tar.gz (276kB): 276kB downloaded
  Running setup.py (path:/tmp/pip_build_root/trollius/setup.py) egg_info for package trollius
    !!! WARNING !!! The Trollius project is now deprecated!
    
    
    warning: no files found matching 'release.py'
    
    !!! WARNING !!! The Trollius project is now deprecated!
Downloading/unpacking greenlet (from neovim)
  Downloading greenlet-0.4.9.tar.gz (54kB): 54kB downloaded
  Running setup.py (path:/tmp/pip_build_root/greenlet/setup.py) egg_info for package greenlet
    
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from trollius->neovim)
Downloading/unpacking futures (from trollius->neovim)
  Downloading futures-3.0.5-py2-none-any.whl
Installing collected packages: neovim, msgpack-python, trollius, greenlet, futures
  Running setup.py install for neovim
    
  Running setup.py install for msgpack-python
    building 'msgpack._packer' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -D__LITTLE_ENDIAN__=1 -I. -I/usr/include/python2.7 -c msgpack/_packer.cpp -o build/temp.linux-x86_64-2.7/msgpack/_packer.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    msgpack/_packer.cpp:4:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    WARNING: Failed to compile extension modules.
    msgpack uses fallback pure python implementation.
    command 'x86_64-linux-gnu-gcc' failed with exit status 1
    building 'msgpack._unpacker' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -D__LITTLE_ENDIAN__=1 -I. -I/usr/include/python2.7 -c msgpack/_unpacker.cpp -o build/temp.linux-x86_64-2.7/msgpack/_unpacker.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    msgpack/_unpacker.cpp:4:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    WARNING: Failed to compile extension modules.
    msgpack uses fallback pure python implementation.
    command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
  Running setup.py install for trollius
    !!! WARNING !!! The Trollius project is now deprecated!
    
    
    warning: no files found matching 'release.py'
    
    !!! WARNING !!! The Trollius project is now deprecated!
  Running setup.py install for greenlet
    building 'greenlet' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-x86_64-2.7/greenlet.o
    In file included from greenlet.c:5:0:
    greenlet.h:8:20: fatal error: Python.h: No such file or directory
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1Rw8g7-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_ext

building 'greenlet' extension

creating build

creating build/temp.linux-x86_64-2.7

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c greenlet.c -o build/temp.linux-x86_64-2.7/greenlet.o

In file included from greenlet.c:5:0:

greenlet.h:8:20: fatal error: Python.h: No such file or directory

 #include <Python.h>

                    ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/greenlet/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-1Rw8g7-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/greenlet
Traceback (most recent call last):
  File "/usr/bin/pip2", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip2')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)
```

After installing `python-dev` everything is OK.

`pip3 install neovim` works fine however.

I don't have the access rights to reopen this issue.

**Comment by bfredl** [comment]
The difference must be because `python3-dev`was already installed. Doesn't python-pip depend on python-dev, at least recommendedly? Because it is seems a general requirement of building any python package on debian, and not neovim specifically? 
I don't think we should clutter the installation instructions with distro-specific issues (not all distro:s split out "dev" packages), but a note in "troubleshooting" would be good.

**Comment by expipiplus1** [comment]
On Ubuntu 14.04 it's just a recommended package. 

I think a note somewhere would be handy, if only for people not familiar with building python packages.

**Comment by tarruda** [comment]
About the python gui dependencies: On a normal ubuntu desktop installation only python-dev is required(eg: to build greenlet), but some python/gobject dependencies are required in other environments. I once wrote a script to install it in ubuntu 12.04(in pyenv) but the instructions can be adapted: https://gist.github.com/tarruda/b67472898a7e4bd81572

**Comment by viccuad** [comment]
@tarruda about python-gui deps on Debian/Ubuntu: https://github.com/neovim/python-gui/issues/5

(I'm Debian's python-client and python-gui maintainer :)

**Comment by justinmk** [comment]
[python-gui](https://github.com/neovim/python-gui) deps are mentioned in its readme. As for this original post of this issue: python-dev is needed only if trollius (python 2.6) or pyuv (python _older than_ 3.4) are required. Given that we fallback to asyncio on python 3.4+, this issue will fade away.
