### ISSUE TITLE
Python client crashes under windows

### ISSUE THREAD

**Issue by RedX2501** [neovim/python-client#152]
Reported under neovim/neovim/issues/3862 and equalsraf/neovim-qt/issues/79

When starting the latest build from equalsraf repo python will not start properly.

The command executed was `:py 42`

My question is how do you debug this? Python quits to fast for me to able able to attach...

The python log file contains:

```
2015-12-16 19:30:08,586 [ERROR @ base_events.py:default_exception_handler:1053] 16700 - Fatal read error on pipe transport
protocol: <neovim.msgpack_rpc.event_loop.asyncio.AsyncioEventLoop object at 0x027314B0>
transport: <_ProactorReadPipeTransport fd=0>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\trollius\proactor_events.py", line 195, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 4096)
  File "C:\Python27\lib\site-packages\trollius\windows_events.py", line 428, in recv
    self._register_with_iocp(conn)
  File "C:\Python27\lib\site-packages\trollius\windows_events.py", line 609, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
WindowsError: [Error 6] Das Handle ist ungültig
```

The neovim log file nvimlog:

```
015/12/16 20:43:55 [error @ call_set_error:743] 17716 - msgpack-rpc: Channel was closed by the client
2015/12/16 20:44:33 [info @ main:533] 16324 - Starting Neovim main loop.
2015/12/16 20:44:41 [error @ forward_stderr:333] 16324 - Channel 2 stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\neovim\__init__.py", line 64, in start_host
    session = stdio_session()
  File "C:\Python27\lib\site-packages\neovim\msgpack_rpc\__init__
2015/12/16 20:44:42 [error @ forward_stderr:333] 16324 - Channel 2 stderr: .py", line 36, in stdio_session
    return session('stdio')
  File "C:\Python27\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 17, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "C:\Python27\lib\site-packages\neovim\m
2015/12/16 20:44:42 [error @ forward_stderr:333] 16324 - Channel 2 stderr: sgpack_rpc\event_loop\base.py", line 88, in __init__
    getattr(self, '_connect_{0}'.format(transport_type))(*args)
  File "C:\Python27\lib\site-packages\neovim\msgpack_rpc\event_loop\asyncio.py", line 90, in _connect_stdio
    self._loop.run_until_co
2015/12/16 20:44:43 [error @ forward_stderr:333] 16324 - Channel 2 stderr: mplete(coroutine)
  File "C:\Python27\lib\site-packages\trollius\base_events.py", line 348, in run_until_complete
    raise RuntimeError('Event loop stopped before Future completed.')
RuntimeError: Event loop stopped before Future completed.

2015/12/16 20:44:43 [error @ call_set_error:743] 16324 - msgpack-rpc: Channel was closed by the client
```

**Comment by prabirshrestha** [comment]
Same with python3 in windows 10.

```
X:\>nvim --cmd "echo has('python3') | q"
1
```

```
X:\>nvim --cmd "python3 42 | q"
function provider#python3#Call..remote#host#Require..<SNR>3_RequirePythonHost, line 15
Vim(if):Channel was closed by the client
Failed to load python3 host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a file and opening the generated log file. Also, the host stderr will be available in Neovim log, so it may contain useful information. See also ~/.nvimlog.Terminal UI disabled at compile time, ignoring console input
Press ENTER or type command to continue^C
```

```
X:\>type python.log_2724
2016-01-29 23:23:09,798 [ERROR @ base_events.py:default_exception_handler:1090] 2724 - Fatal read error on pipe transport
protocol: <neovim.msgpack_rpc.event_loop.asyncio.AsyncioEventLoop object at 0x0000001D8EEB7240>
transport: <_ProactorReadPipeTransport fd=0>
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\asyncio\proactor_events.py", line 195, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 4096)
  File "C:\Program Files\Python35\lib\asyncio\windows_events.py", line 425, in recv
    self._register_with_iocp(conn)
  File "C:\Program Files\Python35\lib\asyncio\windows_events.py", line 606, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6] The handle is invalid
2016-01-29 23:23:09,798 [ERROR @ base_events.py:default_exception_handler:1090] 2724 - Exception in callback _ProactorBasePipeTransport._call_connection_lost(OSError(9, 'T...None, 6, None))
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(OSError(9, 'T...None, 6, None))>
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\asyncio\events.py", line 125, in _run
    self._callback(*self._args)
  File "C:\Program Files\Python35\lib\asyncio\proactor_events.py", line 122, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "C:\Program Files\Python35\lib\site-packages\neovim\msgpack_rpc\event_loop\asyncio.py", line 47, in connection_lost
    self._on_error(exc.message if exc else 'EOF')
AttributeError: 'OSError' object has no attribute 'message'
```

**Comment by equalsraf** [comment]
This seems to be the same as https://github.com/neovim/neovim/issues/4253#issuecomment-184437483

**Comment by freeo** [comment]
Same here, win 7 64, python 3.4.3 64, python-client 68a5066 (2016/02/17).

```
2016-02-18 14:04:17,238 [ERROR @ base_events.py:default_exception_handler:1008] 8740 - Fatal read error on pipe transport
protocol: <neovim.msgpack_rpc.event_loop.asyncio.AsyncioEventLoop object at 0x0000000002EA4358>
transport: <_ProactorReadPipeTransport fd=0>
Traceback (most recent call last):
  File "C:\Python34_64\lib\asyncio\proactor_events.py", line 191, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 4096)
  File "C:\Python34_64\lib\asyncio\windows_events.py", line 425, in recv
    self._register_with_iocp(conn)
  File "C:\Python34_64\lib\asyncio\windows_events.py", line 606, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6] The handle is invalid
2016-02-18 14:04:17,238 [ERROR @ base_events.py:default_exception_handler:1008] 8740 - Exception in callback _ProactorBasePipeTransport._call_connection_lost(OSError(9, 'T...None, 6, None))
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(OSError(9, 'T...None, 6, None))>
Traceback (most recent call last):
  File "C:\Python34_64\lib\asyncio\events.py", line 120, in _run
    self._callback(*self._args)
  File "C:\Python34_64\lib\asyncio\proactor_events.py", line 118, in _call_connection_lost
    self._protocol.connection_lost(exc)
  File "C:\Python34_64\lib\site-packages\neovim\msgpack_rpc\event_loop\asyncio.py", line 47, in connection_lost
    self._on_error(exc.message if exc else 'EOF')
AttributeError: 'OSError' object has no attribute 'message'
```

**Comment by maxwell-k** [comment]
I have the same problem on 64 bit Windows 7, Python 3.4.3, python-client 0.1.0. If I follow the instructions in [neovim/neovim#4253](https://github.com/neovim/neovim/issues/4253#issuecomment-184437483l) changing `.message` to `.args[0]` then I get the same error as that comment:

```
2016-02-23 09:53:55,397 [ERROR @ base_events.py:default_exception_handler:1008] 7764 - Fatal read error on pipe transport
protocol: <neovim.msgpack_rpc.event_loop.asyncio.AsyncioEventLoop object at 0x0286E9B0>
transport: <_ProactorReadPipeTransport fd=0>
Traceback (most recent call last):
  File "C:\Users\maxwellk\AppData\Local\Programs\Python34\lib\asyncio\proactor_events.py", line 191, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 4096)
  File "C:\Users\maxwellk\AppData\Local\Programs\Python34\lib\asyncio\windows_events.py", line 425, in recv
    self._register_with_iocp(conn)
  File "C:\Users\maxwellk\AppData\Local\Programs\Python34\lib\asyncio\windows_events.py", line 606, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6] The handle is invalid

```

**Comment by jmlucjav** [comment]
same here: win2008 R2, python 3.5.1

**Comment by Shougo** [comment]
Related pull request.

https://github.com/neovim/python-client/pull/158

**Comment by justinmk** [comment]
Seems to be fixed. `:py print("42")` works on Windows. We also have automated tests running against python on Windows.
