### ISSUE TITLE
cannot embed

### ISSUE THREAD

**Issue by timeyyy** [neovim/python-client#164]
on ubuntu, python2, neovim installed using apt.

Doing the simple example from the readme gives `nvim = attach('child', argv=['/usr/bin', 'nvim', '--embed'])`

```
File "tk_ui.py", line 577, in <module>
    nvim = attach('child', argv=['/usr/bin', 'nvim', '--embed'])
  File "/home/alfa/Documents/git/python-client/neovim/__init__.py", line 89, in attach
    child_session(argv) if session_type == 'child' else
  File "/home/alfa/Documents/git/python-client/neovim/msgpack_rpc/__init__.py", line 41, in child_session
    return session('child', argv)
  File "/home/alfa/Documents/git/python-client/neovim/msgpack_rpc/__init__.py", line 17, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "/home/alfa/Documents/git/python-client/neovim/msgpack_rpc/event_loop/base.py", line 88, in __init__
    getattr(self, '_connect_{0}'.format(transport_type))(*args)
  File "/home/alfa/Documents/git/python-client/neovim/msgpack_rpc/event_loop/uv.py", line 81, in _connect_child
    stdio=(stdin, stdout, stderr,))
TypeError: Required argument 'loop' (pos 1) not found

```

**Comment by tarruda** [comment]
The first argument should be the program name. Unless you are using a very strange system, "/usr/bin" should be a directory. Just use something like `nvim = attach('child', argv=['nvim', '--embed'])`.(assuming nvim is on PATH, if not just pass the full path of the nvim binary)

**Comment by timeyyy** [comment]
`which nvim` -> `/usr/bin/nvim`

`nvim = attach('child', argv=['nvim', '--embed'])` -> same result as above

**Comment by tarruda** [comment]
> which nvim -> /usr/bin/nvim

I know, but the stack trace you printed contains `nvim = attach('child', argv=['/usr/bin', 'nvim', '--embed'])`, so I assumed you were passing "/usr/bin" as the first argument.

Unfortunately I can't reproduce your error, I just updated my local repo and did the following in the REPL:

```python
>>> import neovim; print neovim.__file__
neovim/__init__.pyc  # to ensure the module from master branch in current directory is being loaded
>>> nvim = neovim.attach('child', argv=['nvim', '--embed'])
>>> nvim.buffers[0][:] = ['line1', 'line2']
>>> nvim.buffers[0][:]
['line1', 'line2']
>>> nvim.quit()
>>>
```

Can you paste a similar interactive python session that reproduces the error?

**Comment by timeyyy** [comment]
```
>>> import neovim;neovim.__file__
'neovim/__init__.pyc'
>>> nvim = neovim.attach('child', argv=['nvim', '--embed'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "neovim/__init__.py", line 89, in attach
    child_session(argv) if session_type == 'child' else
  File "neovim/msgpack_rpc/__init__.py", line 41, in child_session
    return session('child', argv)
  File "neovim/msgpack_rpc/__init__.py", line 17, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "neovim/msgpack_rpc/event_loop/base.py", line 88, in __init__
    getattr(self, '_connect_{0}'.format(transport_type))(*args)
  File "neovim/msgpack_rpc/event_loop/uv.py", line 81, in _connect_child
    stdio=(stdin, stdout, stderr,))
TypeError: Required argument 'loop' (pos 1) not found
```
I'm using python 2.7.6, i'm not sure if that plays a role?

**Comment by tarruda** [comment]
> i guess it's because my python is version 2.7.6?

I don't think so, my system's python version is 2.7.10. Not to mention the repo is regularly tested in multiple python versions(minimum 2.6): https://travis-ci.org/neovim/python-client/builds/109927964
