### ISSUE TITLE
Invoking echoe always causes NvimError

### ISSUE THREAD

**Issue by 5t111111** [neovim/python-client#206]
I've tried to create Python3 plugin and have found invloking `echoe` from python-client (installed via `pip3 install neovim`) always causes `NvimError` (I use vim-plug to load plugins atm) :

```
error caught in async handler '/Users/hirofumiwakasugi/.vim/plugged/nvim-example-python3-plugin/rplugin/python3/nvim-example-python-plugin.py:command:EchoeFro
mPython []':                                                                                                                                                  
NvimError(b'Vim(echoerr):Echoe from Python',)                                                                                                                 
Traceback (most recent call last):                                                                                                                            
  File "/usr/local/lib/python3.5/site-packages/neovim/plugin/host.py", line 91, in _on_notification                                                           
    handler(*args)                                                                                                                                            
  File "/usr/local/lib/python3.5/site-packages/neovim/plugin/host.py", line 160, in decoder                                                                   
    return fn(*walk(decode_if_bytes, args, decode))                                                                                                           
  File "/Users/hirofumiwakasugi/.vim/plugged/nvim-example-python3-plugin/rplugin/python3/nvim-example-python-plugin.py", line 15, in echoe_from_python        
    self.nvim.command('echoe "Echoe from Python"')                                                                                                            
  File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 201, in command                                                                      
    return self.request('vim_command', string, **kwargs)                                                                                                      
  File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 129, in request                                                                      
    res = self._session.request(name, *args, **kwargs)                                                                                                        
neovim.api.nvim.NvimError: b'Vim(echoerr):Echoe from Python' 
```

The whole code is the following, and `:EchoFromPython` works without any problems:

```python
import neovim

@neovim.plugin
class Main(object):
    def __init__(self, nvim):
        self.nvim = nvim

    @neovim.command('EchoFromPython')
    def echo_from_python(self):
        self.nvim.command('echo "Echo from Python"')

    @neovim.command('EchoeFromPython')
    def echoe_from_python(self):
        self.nvim.command('echoe "Echoe from Python"')
```

I've enabled debug logging and got the followings:

```
2016-05-16 16:05:34,778 [DEBUG @ msgpack_stream.py:_on_data:56] 8072 - received message: [2, b'/Users/hirofumiwakasugi/.vim/plugged/nvim-example-python3-plugin/rplugin/python3/nvim-example-python-plugin.py:command:EchoeFromPython', []]
2016-05-16 16:05:34,778 [DEBUG @ async_session.py:_on_notification:102] 8072 - received notification: b'/Users/hirofumiwakasugi/.vim/plugged/nvim-example-python3-plugin/rplugin/python3/nvim-example-python-plugin.py:command:EchoeFromPython', []
2016-05-16 16:05:34,778 [DEBUG @ session.py:_on_notification:216] 8072 - received rpc notification, greenlet <greenlet.greenlet object at 0x10bc3db90> will handle it
2016-05-16 16:05:34,778 [DEBUG @ host.py:_on_notification:89] 8072 - calling notification handler for "/Users/hirofumiwakasugi/.vim/plugged/nvim-example-python3-plugin/rplugin/python3/nvim-example-python-plugin.py:command:EchoeFromPython", args: "[]"
2016-05-16 16:05:34,779 [DEBUG @ msgpack_stream.py:send:33] 8072 - sent [0, 2, 'vim_command', ('echoe "Echoe from Python"',)]
2016-05-16 16:05:34,779 [DEBUG @ base.py:send:113] 8072 - Sending 'b'\x94\x00\x02\xabvim_command\x91\xb9echoe "Echoe from Python"''
2016-05-16 16:05:34,779 [DEBUG @ session.py:_yielding_request:153] 8072 - yielding from greenlet <greenlet.greenlet object at 0x10bc3db90> to wait for response
2016-05-16 16:05:34,779 [DEBUG @ msgpack_stream.py:_on_data:54] 8072 - waiting for message...
2016-05-16 16:05:34,780 [DEBUG @ msgpack_stream.py:_on_data:59] 8072 - unpacker needs more data...
2016-05-16 16:05:34,781 [DEBUG @ msgpack_stream.py:_on_data:54] 8072 - waiting for message...
2016-05-16 16:05:34,781 [DEBUG @ msgpack_stream.py:_on_data:56] 8072 - received message: [1, 2, [0, b'Vim(echoerr):Echoe from Python'], None]
2016-05-16 16:05:34,781 [DEBUG @ async_session.py:_on_response:95] 8072 - received response: [0, b'Vim(echoerr):Echoe from Python'], None
2016-05-16 16:05:34,782 [DEBUG @ session.py:response_cb:149] 8072 - response is available for greenlet <greenlet.greenlet object at 0x10bc3db90>, switching back
2016-05-16 16:05:34,782 [INFO @ session.py:request:97] 8072 - 'Received error: [0, b'Vim(echoerr):Echoe from Python']
```

Do you have any clue?

Thanks in advance.

**Comment by bfredl** [comment]
This is expected, as `echoerr` does raise an error. You probably want `self.nvim.err_write("some error\n")` instead.

**Comment by 5t111111** [comment]
Yes! `self.nvim.err_write("some error\n")` is exactly what I'm looking for. Thank you for the quick response.
