### ISSUE TITLE
Tests fail with python3.5

### ISSUE THREAD

**Issue by jamessan** [neovim/python-client#238]
While @viccuad was working on updating Debian's packaging, it was noticed that the tests are failing with Python 3.5 but not Python 2.7.

It seems to be related to (lack of) availability of some package in the environment because the tests work for @viccuad normally, but not when running inside the build chroot.  For me, it fails both in and out of the chroot.

```
I: pybuild base:184: cd /<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build; python3.5 -m nose test
EEEEEEEE
======================================================================
ERROR: Failure: RuntimeError (Cannot add child handler, the child watcher does not have a loop attached)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_buffer.py", line 3, in <module>
    from test_common import vim, cleanup
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_common.py", line 17, in <module>
    vim = neovim.attach('child', argv=json.loads(child_argv))
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/__init__.py", line 103, in attach
    child_session(argv) if session_type == 'child' else
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 42, in child_session
    return session('child', argv)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 18, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/base.py", line 88, in __init__
    getattr(self, '_connect_{}'.format(transport_type))(*args)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/asyncio.py", line 97, in _connect_child
    self._loop.run_until_complete(coroutine)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1189, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 856, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: RuntimeError (Cannot add child handler, the child watcher does not have a loop attached)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_client_rpc.py", line 3, in <module>
    from test_common import vim, cleanup
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_common.py", line 17, in <module>
    vim = neovim.attach('child', argv=json.loads(child_argv))
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/__init__.py", line 103, in attach
    child_session(argv) if session_type == 'child' else
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 42, in child_session
    return session('child', argv)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 18, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/base.py", line 88, in __init__
    getattr(self, '_connect_{}'.format(transport_type))(*args)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/asyncio.py", line 97, in _connect_child
    self._loop.run_until_complete(coroutine)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1189, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 856, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: RuntimeError (Cannot add child handler, the child watcher does not have a loop attached)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_common.py", line 17, in <module>
    vim = neovim.attach('child', argv=json.loads(child_argv))
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/__init__.py", line 103, in attach
    child_session(argv) if session_type == 'child' else
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 42, in child_session
    return session('child', argv)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 18, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/base.py", line 88, in __init__
    getattr(self, '_connect_{}'.format(transport_type))(*args)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/asyncio.py", line 97, in _connect_child
    self._loop.run_until_complete(coroutine)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1189, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 856, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: RuntimeError (Cannot add child handler, the child watcher does not have a loop attached)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_concurrency.py", line 2, in <module>
    from test_common import vim, cleanup
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_common.py", line 17, in <module>
    vim = neovim.attach('child', argv=json.loads(child_argv))
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/__init__.py", line 103, in attach
    child_session(argv) if session_type == 'child' else
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 42, in child_session
    return session('child', argv)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 18, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/base.py", line 88, in __init__
    getattr(self, '_connect_{}'.format(transport_type))(*args)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/asyncio.py", line 97, in _connect_child
    self._loop.run_until_complete(coroutine)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1189, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 856, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: RuntimeError (Cannot add child handler, the child watcher does not have a loop attached)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_events.py", line 3, in <module>
    from test_common import vim, cleanup
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_common.py", line 17, in <module>
    vim = neovim.attach('child', argv=json.loads(child_argv))
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/__init__.py", line 103, in attach
    child_session(argv) if session_type == 'child' else
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 42, in child_session
    return session('child', argv)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 18, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/base.py", line 88, in __init__
    getattr(self, '_connect_{}'.format(transport_type))(*args)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/asyncio.py", line 97, in _connect_child
    self._loop.run_until_complete(coroutine)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1189, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 856, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: RuntimeError (Cannot add child handler, the child watcher does not have a loop attached)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_tabpage.py", line 3, in <module>
    from test_common import vim, cleanup
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_common.py", line 17, in <module>
    vim = neovim.attach('child', argv=json.loads(child_argv))
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/__init__.py", line 103, in attach
    child_session(argv) if session_type == 'child' else
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 42, in child_session
    return session('child', argv)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 18, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/base.py", line 88, in __init__
    getattr(self, '_connect_{}'.format(transport_type))(*args)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/asyncio.py", line 97, in _connect_child
    self._loop.run_until_complete(coroutine)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1189, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 856, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: RuntimeError (Cannot add child handler, the child watcher does not have a loop attached)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_vim.py", line 4, in <module>
    from test_common import vim, cleanup
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_common.py", line 17, in <module>
    vim = neovim.attach('child', argv=json.loads(child_argv))
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/__init__.py", line 103, in attach
    child_session(argv) if session_type == 'child' else
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 42, in child_session
    return session('child', argv)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 18, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/base.py", line 88, in __init__
    getattr(self, '_connect_{}'.format(transport_type))(*args)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/asyncio.py", line 97, in _connect_child
    self._loop.run_until_complete(coroutine)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1189, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 856, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: RuntimeError (Cannot add child handler, the child watcher does not have a loop attached)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_window.py", line 3, in <module>
    from test_common import vim, cleanup
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/test/test_common.py", line 17, in <module>
    vim = neovim.attach('child', argv=json.loads(child_argv))
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/__init__.py", line 103, in attach
    child_session(argv) if session_type == 'child' else
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 42, in child_session
    return session('child', argv)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/__init__.py", line 18, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/base.py", line 88, in __init__
    getattr(self, '_connect_{}'.format(transport_type))(*args)
  File "/<<PKGBUILDDIR>>/.pybuild/pythonX.Y_3.5/build/neovim/msgpack_rpc/event_loop/asyncio.py", line 97, in _connect_child
    self._loop.run_until_complete(coroutine)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1189, in subprocess_exec
    bufsize, **kwargs)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 194, in _make_subprocess_transport
    self._child_watcher_callback, transp)
  File "/usr/lib/python3.5/asyncio/unix_events.py", line 856, in add_child_handler
    "Cannot add child handler, "
RuntimeError: Cannot add child handler, the child watcher does not have a loop attached
-------------------- >> begin captured logging << --------------------
asyncio: DEBUG: Using selector: EpollSelector
--------------------- >> end captured logging << ---------------------
```

**Comment by jamessan** [comment]
> It seems to be related to (lack of) availability of some package in the environment

By this I mean that the packages pulled in by the build (listed below) satisfy all the declared requirements, but the testing fails.  Yet, in a "dirty" environment which has all the declared requirements plus packages pulled in by other installed software, the tests work.

```
 debhelper (>= 9),
 dh-python,
 python-all (>= 2.6.6-3~),
 python-setuptools,
 python3-all,
 python3-setuptools,
# dependencies for python2:
 python-msgpack (>= 0.4.0),
 python-greenlet,
 cython,
 python-trollius,
# dependencies for python3:
 python3-msgpack (>= 0.4.0),
 python3-greenlet,
# dependencies for tests:
 neovim (>= 0.1.6),
 python-nose,
 python3-nose
```

**Comment by meiralins** [comment]
In a clean virtualenv, tests passes for me in 3.5.0, 3.5.1 and 3.5.2.
But 3.6 is failing with these errors.

I'm not very proficient in asyncio, but I will take a look on this later.

**Comment by meiralins** [comment]
Also, using 3.6, my completion system(deoplete-jedi) stopped working but :SystemCheck shows everything is fine.

**Comment by meiralins** [comment]
@jamessan one package that apparently fix the tests is the pyuv.
But only if you use an 0.10.x or older version.
#240 fixes for new versions.
