### ISSUE TITLE
crash with inspect.py file in current dir

### ISSUE THREAD

**Issue by lutostag** [neovim/python-client#256]
versions:
> OS: Ubuntu 17.04 (Zesty Zapus)
> neovim: 0.1.7ubuntu1+git201704120121+3332+23~ubuntu17.04.1
> python3: 3.5.3
> pip3 neovim: 0.1.13

So this has been happening since I can recall, but I've finally got it tracked down. [

minimal repro:
```
touch inspect.py
nvim --noplugin inspect.py
```
then just run :py3 1

output from messages is as follows:
```
:py3 1
function provider#python3#Call[9]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):ch 1 was closed by the client
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/neovim/msgpack_rpc/event_loop/__init__.py", line 7, in <module>
    from .uv import UvEventLoop
  File "/usr/local/lib/python3.5/dist-packages/neovim/msgpack_rpc/event_loop/uv.py", line 5, in <module>
    import pyuv
ImportError: No module named 'pyuv'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/neovim/__init__.py", line 16, in <module>
    from .msgpack_rpc import (ErrorResponse, child_session, socket_session,
  File "/usr/local/lib/python3.5/dist-packages/neovim/msgpack_rpc/__init__.py", line 8, in <module>
    from .event_loop import EventLoop
  File "/usr/local/lib/python3.5/dist-packages/neovim/msgpack_rpc/event_loop/__init__.py", line 12, in <module>
    from .asyncio import AsyncioEventLoop
  File "/usr/local/lib/python3.5/dist-packages/neovim/msgpack_rpc/event_loop/asyncio.py", line 19, in <module>
    import asyncio
  File "/usr/lib/python3.5/asyncio/__init__.py", line 21, in <module>
    from .base_events import *
  File "/usr/lib/python3.5/asyncio/base_events.py", line 36, in <module>
    from . import tasks
  File "/usr/lib/python3.5/asyncio/tasks.py", line 327, in <module>
    def wait(fs, *, loop=None, timeout=None, return_when=ALL_COMPLETED):
  File "/usr/lib/python3.5/asyncio/coroutines.py", line 205, in coroutine
    if inspect.isgeneratorfunction(func):
AttributeError: module 'inspect' has no attribute 'isgeneratorfunction'
```
***
This is happening because python injects the working directory between my PYTHONPATH* and SYSTEMPATH* on startup. Just removing '' is not enough.

To verify that:
```
python -c 'import sys; print(sys.path)'
```
and indeed my local directory is in there...

This is kind of a hack to work around the fact that python by default thinks local directories should be imported before system libraries, but so was #55, seems like it just didn't go far enough.

the following hack fixes it for me:
```python
cwd = os.getcwd()
if cwd in sys.path:     
    sys.path.remove(cwd)
    sys.path.append(cwd) # which pushes the working directory after systempaths
```
just after the necessary imports in  \_\_init\_\_.py [here](https://github.com/neovim/python-client/blob/master/neovim/__init__.py#L8)
***
Whew!

Now further this is not a complete solution... This just kicks the can down the road... If someone were to now do this with the imports before our hack, (say create an os.py or loggiing.py -- this would happen again) [for some reason sys.py does not hit this, it must be more of a builtin and can't be overloaded, at least in my limited testing]. So I would recommend moving the `import logging` to below this hack as well.

As for the `import os`, not sure how to get around that, there are a few promising leads:
* since py3.4 at least the [isolated mode](https://docs.python.org/3.5/using/cmdline.html#cmdoption-I) option that can be looked into further -- but will require more hacking to reorder the imports most people would expect to work.
* some hacks only using builtins and sys could be worked out, a few might work, but none are pretty...

Otherwise the case will be solved except for the os.py case, which will still stick around unfortunately.

Welcome your thoughts, and thought I should file it as a bug for discussion before submitting a PR.

Thanks! I really appreciate all of you all's hard work!

P.S. Also not sure if it should be fixed here or at where neovim loads this [here](https://github.com/neovim/neovim/blob/master/runtime/autoload/provider/pythonx.vim#L25)

P.P.S. I know python developers are supposed to know better than calling files the same as builtin modules, but someone on my team from years ago did it, and were a bit stuck now. Also having and editor fall over because a file with a certain name exists is kinda silly.

**Comment by lutostag** [comment]
And realized I'm a shmuck... It's entirely my fault. Had an extra : appended to my PYTHONPATH. please ignore. Sorry for the noise.
