### ISSUE TITLE
Python 3.7a2: SyntaxError (invalid syntax)

### ISSUE THREAD

**Issue by vaxXxa** [neovim/python-client#277]
I've installed `Python 3.7a2`, created virtualenv `neovim3` and got the follow:

```function remote#host#UpdateRemotePlugins[6]..<SNR>76_RegistrationCommands[15]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):ch 1 was closed by the client
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../neovim3/lib/python3.7/site-packages/neovim/__init__.py", line 9, in <module>
    from .api import Nvim
  File ".../neovim3/lib/python3.7/site-packages/neovim/api/__init__.py", line 7, in <module>
    from .buffer import Buffer
  File ".../neovim3/lib/python3.7/site-packages/neovim/api/buffer.py", line 101
    col_end=-1, src_id=-1, async=None):
                               ^
SyntaxError: invalid syntax
function remote#host#UpdateRemotePlugins[6]..<SNR>76_RegistrationCommands[15]..remote#host#Require[10]..provider#pythonx#Require, line 25
Failed to load python3 host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available
in messages.
remote/host: generated rplugin manifest: .../.local/share/nvim/rplugin.vim```

**Comment by bfredl** [comment]
#274
