### ISSUE TITLE
PackOverflowError when trying to import the neovim client

### ISSUE THREAD

**Issue by akrejczinger** [neovim/python-client#318]
```
bpython version 0.16 on top of Python 3.4.3 /usr/bin/python3
>>> import neovim
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import neovim
  File "/home/arpadkrejczinger/.local/lib/python3.4/site-packages/neovim/__init__.py", line 9, in <module>
    from .api import Nvim
  File "/home/arpadkrejczinger/.local/lib/python3.4/site-packages/neovim/api/__init__.py", line 7, in <module>
    from .buffer import Buffer
  File "/home/arpadkrejczinger/.local/lib/python3.4/site-packages/neovim/api/buffer.py", line 2, in <module>
    from .common import Remote
  File "/home/arpadkrejczinger/.local/lib/python3.4/site-packages/neovim/api/common.py", line 4, in <module>
    from msgpack import unpackb
  File "/usr/local/lib/python3.4/dist-packages/msgpack/__init__.py", line 28, in <module>
    from msgpack.fallback import Packer, unpackb, Unpacker
  File "/usr/local/lib/python3.4/dist-packages/msgpack/fallback.py", line 52, in <module>
    from msgpack.exceptions import (
ImportError: cannot import name 'PackOverflowError'
```

**Comment by numirias** [comment]
Are you using the latest `msgpack` version? What does `msgpack.version` say?

**Comment by akrejczinger** [comment]
I'm not sure what the issue was. Uninstalling and reinstalling msgpack fixed it.

**Comment by dsummersl** [comment]
I had a similar problem - `pip3 uninstall msgpack` (and reinstall) fixed the problem for me.

**Comment by MoHD20** [comment]
I just installed neovim using brew and had this same problem. Solution was reinstalling msgpack.
