### ISSUE TITLE
pyuv 1.0.2 changed API for Process.spawn

### ISSUE THREAD

**Issue by diefans** [neovim/python-client#88]
`pyuv==1.0.2` changed its API a bit...

```
Traceback (most recent call last):
  File "/usr/local/bin/pynvim", line 9, in <module>
    load_entry_point('neovim==0.0.27', 'console_scripts', 'pynvim')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/neovim/ui/cli.py", line 60, in main
    nvim = attach('child', argv=nvim_argv)
  File "/usr/local/lib/python2.7/dist-packages/neovim/__init__.py", line 88, in attach
    child_session(argv) if session_type == 'child' else
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/__init__.py", line 41, in child_session
    return session('child', argv)
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/__init__.py", line 17, in session
    loop = EventLoop(transport_type, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/event_loop/base.py", line 88, in __init__
    getattr(self, '_connect_{0}'.format(transport_type))(*args)
  File "/usr/local/lib/python2.7/dist-packages/neovim/msgpack_rpc/event_loop/uv.py", line 81, in _connect_child
    stdio=(stdin, stdout, stderr,))
TypeError: Required argument 'loop' (pos 1) not found
```

**Comment by whitelynx** [comment]
Confirming this; this error is preventing me from using either `pynvim` or [`pytknvim`](https://github.com/timeyyy/pytknvim) after fresh installs.
